/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package softwareproject;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.sql.*;

class AppTest {
    App app =new App();
    Connection conn=DBconnect.connect();
    @Test
    void appValidate(){
        String[] expectedOutput={"Amit Kumar","s"};
        assertArrayEquals(expectedOutput,ValidateUsers.validate("2020csb1070@iitrpr.ac.in", "2020csb1070", conn));
    }
}
