/*
 * This Java source file was generated by the Gradle 'init' task.
 * psql
 * executeUpdate() : This method is used for execution of DML statement(INSERT, UPDATE and DELETE) 
 * which is return int value, count of the affected rows.
 *executeQuery() : This method is used to retrieve data from database using SELECT query. 
 *This method returns the ResultSet object that returns the data according to the query.
 */

package softwareproject;
import java.sql.*;
// import java.sql.Connection;
// import java.sql.Statement;
// import java.sql.DriverManager;
// import java.sql.ResultSet;
// import java.sql.SQLException;

public class App {
    
    private final String url = "jdbc:postgresql://localhost/miniproject";
    private final String user = "postgres";
    private final String password = "Amit@7870";

    public Connection connect() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected to the PostgreSQL server successfully.");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return conn;
    }
    public static void main(String[] args) {
        App app= new App();
        Connection conn = app.connect();
        try {
            Statement statement = conn.createStatement();
            String query="SELECT * FROM t";
            ResultSet rs = statement.executeQuery(query);
            ResultSetMetaData resultSetMetaData = rs.getMetaData(); 
            System.out.println("Table name: "+resultSetMetaData.getTableName(1));
            System.out.println("Column name: "+resultSetMetaData.getColumnName(1));
            System.out.println("Column type: "+resultSetMetaData.getColumnTypeName(1));
            System.out.println();

            while(rs.next()){
                System.out.println(rs.getString(1));
            }
            
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
