/*
 * This Java source file was generated by the Gradle 'init' task.

 * psql
 */

package softwareproject;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

public class App {
    
    private final String url = "jdbc:postgresql://localhost/postgres";
    private final String user = "postgres";
    // private final String password = "iitropar";
    private final String password = "Amit@7870";

    public Connection connect() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected to the PostgreSQL server successfully.");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return conn;
    }
    public static void main(String[] args) {
        App app= new App();
        Connection conn = app.connect();
        try {
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM CLASSES");
            while(resultSet.next()){
                System.out.println(resultSet.getString(1));
            }
            
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
